[package]
name = "platformer"
version = "0.1.0"
authors = ["Jacob Fenton <jacob.d.fenton@gmail.com>"]

[[bin]]
name = "platformer"
doc = false

[dependencies]
sdl2 = "0.8"
sdl2_image = "0.2.1"
find_folder = "*"
flate2 = "0.2"
rustc-serialize = "0.3"
